name: restaurant
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sizer: ^3.0.5
  hexcolor: ^3.0.1
  get_it: ^8.0.3
  dartz: ^0.10.1
  svg_flutter: ^0.0.1
  bubble: ^1.2.1
  emoji_picker_flutter: ^4.3.0
  url_launcher: ^6.3.1
  intl: ^0.18.1
  dlibphonenumber: ^1.1.41
  fl_chart: ^1.0.0
  go_router: ^15.1.3
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_assets: ^0.0.6  # <- Make sure this is added under dev_dependencies

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen/Sen-VariableFont_wght.ttf

# 👇 This must be OUTSIDE the flutter block
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/
  filename: icons.dart
